site_name: Apunts de matemàtiques per Batxillerat
theme:
  name: material
  language: ca
  palette:
    primary: indigo
    accent: light blue
  features:
    - navigation.tabs      # Menú superior per a les grans seccions
    - navigation.sections  # Menú lateral organitzat

markdown_extensions:
  - pymdownx.arithmatex:   # L'extensió per a matemàtiques
      generic: true
  - admonition             # Per crear "notes" o "avisos" destacats
  - pymdownx.details       # Per fer desplegables (ex: solucions d'exercicis)
  - attr_list              # Per poder enquadrar i definir % de les imatges
  #- pymdownx.superfencesss

extra_javascript:
  #- https://polyfill.io/v3/polyfill.min.js?features=es6 #no activar mai sembla que es phishing
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Geometria Analítica:
      - "Vectors al pla": geometria/01_vectors.md
      - "Sistema de referència i punts al pla": geometria/02_geometria_pla.md
      - "Equacions de la recta": geometria/03_recta.md 
      - "Paral·lelisme i perpendicularitat": geometria/04_perpendicularitat i parallelisme.md   
      - "Posició relativa de dues rectes": geometria/05_posicio_rectes.md
      - "Mètrica al pla": geometria/06_metrica_pla.md
  - Anàlisi matemàtica:
    - Funcions:
      - "Concepte de funció. Domini i recorregut": analisi/01_concepte_funcio.md
      - "Càlculs bàsics per trobar dominis": analisi/02_eines_calcul_dominis.md
      - "Les funcions elementals": analisi/03_funcions_elementals.md
      - "Transformacions de funcions": analisi/04_transformacio_funcions.md
      - "Operacions amb funcions": analisi/05_operacions_funcions.md
      - "Funcions en valor absolut": analisi/06_funcions_valor_absolut.md
      - "Composició de funcions i funció inversa": analisi/07_composicio_inversa_funcions.md
    - Límits i continuïtat:
      - "Concepte i càlcul de límits a infinit": analisi/08_limits_infinit.md
      - "Concepte de límit en un punt": analisi/09_limits_punt.md
      - "Continuïtat de funcions. Discontinuïtats": analisi/10_continuitat_discontinuitat.md
      - "Càlcul de límits en un punt": analisi/11_calcul_limits_punt.md