site_name: Apunts de matemàtiques per Batxillerat
theme:
  name: material
  language: ca
  palette:
    primary: indigo
    accent: light blue
  features:
    - navigation.tabs      # Menú superior per a les grans seccions
    - navigation.sections  # Menú lateral organitzat

markdown_extensions:
  - pymdownx.arithmatex:   # L'extensió per a matemàtiques
      generic: true
  - admonition             # Per crear "notes" o "avisos" destacats
  - pymdownx.details       # Per fer desplegables (ex: solucions d'exercicis)
  - attr_list              # Per poder enquadrar i definir % de les imatges
  #- pymdownx.superfencesss

plugins:
  - include-markdown:
      opening_tag: "{%"
      closing_tag: "%}"
      preserve_includer_indent: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Geometria Analítica:
      - "Vectors al pla": geometria/01_vectors.md
      - "Sistema de referència i punts al pla": geometria/02_geometria_pla.md
      - "Equacions de la recta": geometria/03_recta.md 
      - "Paral·lelisme i perpendicularitat": geometria/04_perpendicularitat i parallelisme.md   
      - "Posició relativa de dues rectes": geometria/05_posicio_rectes.md
      - "Mètrica al pla": geometria/06_metrica_pla.md
  - Anàlisi matemàtica:
      - "Concepte de funció. Domini i recorregut": geometria/01_vectors.md